<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Authors>MiraFolio contributors</Authors>
    <Copyright>Copyright © 2026 MiraFolio contributors</Copyright>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/nexalify/MiraFolio-Windows</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
